### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by JohnDeeBDD** [rioastamal/lightsail-miab-installer#1]
sh lightsail-miab-installer.sh --installation-id demo --az ap-southeast-1c --email 'admin@wp-fcfs.com' --password 'Password123$' --hostname box.wp-fcfs.com

gets me:
lightsail-miab-installer.sh: 1395: Bad substitution

**Comment by rioastamal** [comment]
@JohnDeeBDD What is your OS and your shell?

**Comment by rioastamal** [comment]
I just added support for zsh and macOS in the latest release v1.1. Please download the latest version.
