### ISSUE TITLE
--dry-run causes error.

### ISSUE THREAD

**Issue by batteredhedgehog** [rioastamal/lightsail-miab-installer#3]
Great script, thanks for the work.

using --dry-run as last parameter gives:
`lightsail-miab-installer.sh: 1521: shift: can't shift that many`

shouldn't be a shift on line 1479.

can workaround using a dummy argument:  --dry-run dummy

**Comment by rioastamal** [comment]
@batteredhedgehog How do I reproduce your error? It works as expected on Bash shell. What's your OS and shell?

**Comment by rioastamal** [comment]
@batteredhedgehog Should be fixed by commit 04d5be85f6, please pull the last update.
